version: '3'

services:
  airflow:
    image: apache/airflow:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=etl_staging
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=etl_aggregated
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
